import React from 'react';
import { motion } from 'motion/react';
import { 
  ArrowLeft, 
  Download, 
  Printer, 
  FileText, 
  TrendingUp, 
  AlertCircle,
  CheckCircle2,
  Database
} from 'lucide-react';
import { YearlyRevenue, Scenario } from '../types/policy';

interface ReportViewProps {
  data: YearlyRevenue[];
  state: Scenario;
  onBack: () => void;
}

export default function ReportView({ data, state, onBack }: ReportViewProps) {
  const currentYearData = data[0];
  const projectedYearData = data[data.length - 1];
  
  const currentRevenue = currentYearData?.net || 0;
  const projectedRevenue = projectedYearData?.net || 0;
  const totalGrowth = ((projectedRevenue - currentRevenue) / currentRevenue) * 100;

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
      notation: 'compact'
    }).format(value);
  };

  return (
    <div className="min-h-screen bg-gray-50 p-4 md:p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center justify-between mb-8 no-print">
          <button 
            onClick={onBack}
            className="flex items-center gap-2 text-gray-600 hover:text-[#004a99] transition-colors font-medium"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </button>
          <div className="flex gap-3">
            <button className="flex items-center gap-2 bg-white border border-gray-200 px-4 py-2 rounded-lg text-sm font-bold hover:bg-gray-50 transition-colors shadow-sm">
              <Printer className="w-4 h-4" />
              Print
            </button>
            <button className="flex items-center gap-2 bg-[#004a99] text-white px-4 py-2 rounded-lg text-sm font-bold hover:bg-[#003a7a] transition-colors shadow-lg shadow-blue-900/10">
              <Download className="w-4 h-4" />
              Download PDF
            </button>
          </div>
        </div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white shadow-xl rounded-2xl overflow-hidden border border-gray-100"
        >
          {/* Report Header */}
          <div className="bg-[#004a99] p-8 text-white">
            <div className="flex justify-between items-start">
              <div>
                <h1 className="text-3xl font-bold mb-2">25-Year Revenue Forecast Report</h1>
                <p className="text-blue-100 opacity-80">Scenario: {state.name} ({state.id})</p>
                <div className="mt-2 flex items-center gap-2">
                  <span className="px-2 py-0.5 bg-white/20 rounded text-[10px] font-bold uppercase tracking-wider">Page: Report Summary</span>
                </div>
              </div>
              <div className="bg-[#ffc72c] p-3 rounded-xl">
                <Database className="w-8 h-8 text-[#004a99]" />
              </div>
            </div>
            <div className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-6 border-t border-white/10 pt-6">
              <div>
                <p className="text-[10px] uppercase tracking-wider opacity-60">Horizon</p>
                <p className="font-bold">2025 - 2050</p>
              </div>
              <div>
                <p className="text-[10px] uppercase tracking-wider opacity-60">View Mode</p>
                <p className="font-bold">{state.viewMode}</p>
              </div>
              <div>
                <p className="text-[10px] uppercase tracking-wider opacity-60">Status</p>
                <p className="font-bold flex items-center gap-1">
                  <CheckCircle2 className="w-3 h-3 text-green-400" />
                  Verified Run
                </p>
              </div>
              <div>
                <p className="text-[10px] uppercase tracking-wider opacity-60">Generated By</p>
                <p className="font-bold">DelDOT Analyst</p>
              </div>
            </div>
          </div>

          <div className="p-8 space-y-10">
            {/* Executive Summary */}
            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-[#004a99]" />
                Executive Summary
              </h2>
              <div className="bg-blue-50 p-6 rounded-xl border border-blue-100">
                <p className="text-gray-700 leading-relaxed">
                  The proposed policy scenario <span className="font-bold">{state.id}</span> projects a net revenue shift from 
                  <span className="font-bold text-[#004a99]"> {formatCurrency(currentRevenue)}</span> in 2025 to 
                  <span className="font-bold text-[#004a99]"> {formatCurrency(projectedRevenue)}</span> by 2050. 
                  This represents a <span className="font-bold text-green-600">{totalGrowth.toFixed(1)}%</span> change over the 25-year horizon.
                </p>
              </div>
            </section>

            {/* Active Mechanisms */}
            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-6">Active Revenue Mechanisms</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {state.mechanisms.filter(m => m.enabled).map(mech => (
                  <div key={mech.id} className="border border-gray-100 p-4 rounded-xl bg-gray-50 flex justify-between items-center">
                    <div>
                      <h3 className="font-bold text-[#004a99] text-sm">{mech.id.replace(/_/g, ' ')}</h3>
                      <p className="text-[10px] text-gray-400">Indexing: {mech.indexing}</p>
                    </div>
                    <span className="font-mono font-bold text-gray-700">{mech.value}</span>
                  </div>
                ))}
              </div>
            </section>

            {/* Recommendations */}
            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <AlertCircle className="w-5 h-5 text-[#ffc72c]" />
                Strategic Impacts
              </h2>
              <div className="space-y-4">
                <div className="p-4 border-l-4 border-[#004a99] bg-gray-50">
                  <h4 className="font-bold text-sm text-gray-900">MBUF Integration</h4>
                  <p className="text-xs text-gray-500 mt-1">The system automatically credits fuel taxes paid against the mileage-based fee to prevent double taxation, as per legislative requirements.</p>
                </div>
                <div className="p-4 border-l-4 border-[#ffc72c] bg-gray-50">
                  <h4 className="font-bold text-sm text-gray-900">Fleet Electrification</h4>
                  <p className="text-xs text-gray-500 mt-1">Projections account for the ACC II mandate, assuming 82% zero-emission vehicle sales by 2032, significantly impacting traditional fuel tax streams.</p>
                </div>
              </div>
            </section>

            {/* Footer */}
            <div className="pt-10 border-t border-gray-100 flex flex-col md:flex-row justify-between items-center gap-4">
              <div className="text-center md:text-left">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Authorized By</p>
                <p className="text-sm font-bold text-gray-900">DelDOT Financial Oversight Committee</p>
              </div>
              <div className="text-right">
                <p className="text-[10px] text-gray-400 uppercase font-bold">Confidentiality</p>
                <p className="text-[10px] text-gray-600 font-bold">LEVEL 3 - RESTRICTED</p>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
